In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
###sentences
sent=['The glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am a good boy',
      'I am a good developer',
      'Understand the meaning of words',
      'your videos are good',]

In [3]:
sent

['The glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are good']

In [4]:
##Define the vocabulary size
voc_size=10000

In [5]:
#One hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3300, 8319, 74, 2090],
 [3300, 8319, 74, 9856],
 [3300, 7206, 74, 838],
 [7287, 6723, 6775, 5880, 3791],
 [7287, 6723, 6775, 5880, 1291],
 [6252, 3300, 8324, 74, 7238],
 [7457, 8675, 7853, 5880]]

In [6]:
##word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3300 8319   74 2090]
 [   0    0    0    0 3300 8319   74 9856]
 [   0    0    0    0 3300 7206   74  838]
 [   0    0    0 7287 6723 6775 5880 3791]
 [   0    0    0 7287 6723 6775 5880 1291]
 [   0    0    0 6252 3300 8324   74 7238]
 [   0    0    0    0 7457 8675 7853 5880]]


In [8]:
##feature represntation
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 188ms/step


array([[[-0.02681576,  0.03562012, -0.04742116,  0.0496862 ,
          0.02830883, -0.01372367,  0.02182844, -0.01688766,
         -0.04989642, -0.00968114],
        [-0.02681576,  0.03562012, -0.04742116,  0.0496862 ,
          0.02830883, -0.01372367,  0.02182844, -0.01688766,
         -0.04989642, -0.00968114],
        [-0.02681576,  0.03562012, -0.04742116,  0.0496862 ,
          0.02830883, -0.01372367,  0.02182844, -0.01688766,
         -0.04989642, -0.00968114],
        [-0.02681576,  0.03562012, -0.04742116,  0.0496862 ,
          0.02830883, -0.01372367,  0.02182844, -0.01688766,
         -0.04989642, -0.00968114],
        [ 0.04166492, -0.01158131, -0.03289529, -0.04936916,
          0.00882947, -0.04331456, -0.03740624, -0.04058076,
         -0.04500837, -0.0438576 ],
        [-0.03303202,  0.04006486, -0.00288773,  0.02237907,
          0.02074752, -0.02568263, -0.02806417,  0.00750069,
          0.02635992,  0.01376916],
        [ 0.04022067, -0.03811691, -0.01570047,  0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 3300, 8319,   74, 2090])